pipeline {
    
    agent {
        docker {
            image 'node:8-alpine'
            args '-p 8080:8080'
        }
    }
    
    environment {
        CI = 'true'
        FIREBASE_DEPLOY_TOKEN = credentials('firebase_deploy_token')
    }
    
    stages {
        stage('Build') {
            steps {
                sh 'npm install'
            }
        }
        stage('Test') {
            steps {
                sh './jenkins/scripts/test.sh'
            }
        }
        stage('Staging') {
            steps {
                sh './jenkins/scripts/staging.sh'
                input message: 'Finished using the Staging version of the Web App? (Click "Proceed" to continue)'
            }
        }
        stage('Production') {
            steps {
                sh './jenkins/scripts/deploy.sh'
            }
        }
    }
}
